name: Deploy to Staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
    - name: SSH into Server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
        ssh -i ~/ssh_key azureuser@74.225.216.162
        cd Monorepo_Deplyment/ && git pull
        pnpm install
        pnpm build
        pm2 restart web-server
        pm2 restart http-server
        pm2 restart ws-server
